# ruff: noqa: E501 — the module is mostly an embedded bash template; line length
# is governed by the generated shell script, not Python style.
"""Generate the standalone shared ``clive`` consumer launcher.

Plain ``clive`` discovers releases from the published endpoint document and
points Claude Code or Codex directly at the selected engine. Hosted frontier
slots are compiled in only for the explicit ``hybrid`` launch mode; discovery
failure never enters the hosted proxy path.
"""

from __future__ import annotations

import shlex
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from imas_ambix.agent.profile import SiteConfig

# The harness reads CLAUDE_CODE_AUTO_COMPACT_WINDOW ahead of the model's default
# window, and the picker maps every served release to a Sonnet-class
# ``behavesAs``, so without this export auto-compaction fires at Sonnet's 200k
# default rather than the release's own budget. The ceiling keeps the window
# below the full usable input budget (about 480k for a 4xH200 dsv4.1-flash
# release): with 14 running sessions near their ceiling that budget would hold
# about 6M KV against a 4M device pool. Compacting near 270k-285k costs far
# fewer compactions than 200k while the lane's memory cap and prefix-hit guard
# absorb the larger contexts. A release whose usable budget is smaller than the
# ceiling compacts at its own budget.
AUTO_COMPACT_WINDOW_CEILING = 300_000


def generate_clive_script(
    site: SiteConfig,
    *,
    mode: str = "local",
    openrouter_native_release: str | None = None,
) -> str:
    """Render a launcher for the explicitly selected model-scope mode."""
    from imas_ambix.agent.litellm_service import LITELLM_PORT

    if mode not in {"local", "hybrid"}:
        raise ValueError("mode must be one of: local, hybrid")
    if mode == "hybrid" and not openrouter_native_release:
        raise ValueError("hybrid mode requires an OpenRouter native release")
    if mode == "local" and openrouter_native_release is not None:
        raise ValueError("an OpenRouter native release requires hybrid mode")

    default_origin = site.__class__.model_fields["global_origin"].default
    legacy_origin = site.global_origin if site.global_origin != default_origin else ""
    endpoint_document = str(site.endpoint_document)
    preferred_release_id = site.preferred_release_id or ""
    proxy_native_release = openrouter_native_release or ""
    template = r"""#!/usr/bin/env bash
# clive — drive an agent CLI against the site model catalog.
#
# GENERATED by the Ambix operator tooling. Do not edit in place; update the
# generator and deploy it again.
#
# Usage:
#   clive [--claude|--codex] [--mode local|hybrid] [--list]
#         [--selector RELEASE[@NxFAMILY]|--model RELEASE]
#         [--worker-profile PATH] [agent-args...]

set -euo pipefail

GLOBAL_ORIGIN=__GLOBAL_ORIGIN__
ENDPOINT_DOCUMENT=__ENDPOINT_DOCUMENT__
PREFERRED_RELEASE_ID=__PREFERRED_RELEASE_ID__
OPENROUTER_NATIVE_RELEASE=__OPENROUTER_NATIVE_RELEASE__
LITELLM_PORT="__LITELLM_PORT__"
LITELLM_SERVICE="imas-ambix-llm.service"
HARNESS="claude"
SELECTOR=""
WORKER_PROFILE=""
LIST_ONLY=false
MODE="local"

usage() {
    cat >&2 <<'USAGE'
clive — drive an agent CLI against the site model catalog.

  clive [--claude|--codex] [--mode local|hybrid] [--list]
        [--selector RELEASE[@NxFAMILY]|--model RELEASE] [agent-args...]

  --claude   Claude Code via the Anthropic Messages API (default).
  --codex    OpenAI Codex CLI via the OpenAI API.
  --mode MODE
             Model scope: local or hybrid (default: local). Hybrid adds the
             hosted frontier slots after global selection.
  --list     List the global catalog and exit.
  --selector RELEASE[@NxFAMILY]
             Select an exact release id or release-at-topology label.
  --model RELEASE
             Alias for selecting an exact release id.
  --worker-profile PATH
             Load a role digest, MCP configuration and built-in tool list.
USAGE
}

ARGS=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --claude) HARNESS="claude"; shift ;;
        --codex) HARNESS="codex"; shift ;;
        --mode)
            [[ $# -ge 2 ]] || { echo "clive: --mode requires one of: local, hybrid." >&2; exit 2; }
            case "$2" in
                local|hybrid) MODE="$2" ;;
                *) echo "clive: invalid mode '$2'; valid values: local, hybrid." >&2; exit 2 ;;
            esac
            shift 2 ;;
        --list) LIST_ONLY=true; shift ;;
        --selector|--model)
            [[ $# -ge 2 ]] || { echo "clive: $1 requires a value." >&2; exit 2; }
            [[ -z "$SELECTOR" ]] || { echo "clive: select a model only once." >&2; exit 2; }
            SELECTOR="$2"; shift 2 ;;
        --worker-profile)
            [[ $# -ge 2 ]] || { echo "clive: --worker-profile requires a path." >&2; exit 2; }
            [[ -z "$WORKER_PROFILE" ]] || { echo "clive: worker profile may be selected only once." >&2; exit 2; }
            WORKER_PROFILE="$2"; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        --) shift; ARGS+=("$@"); break ;;
        *) ARGS+=("$1"); shift ;;
    esac
done

INTERACTIVE=false
[[ -t 0 ]] && INTERACTIVE=true
if _CATALOG_RESULT="$(python3 - "$ENDPOINT_DOCUMENT" "$GLOBAL_ORIGIN" "$SELECTOR" "$LIST_ONLY" "$INTERACTIVE" "$MODE" "$PREFERRED_RELEASE_ID" 3<&0 <<'PY'
import json
import os
import sys
import urllib.error
import urllib.request

(
    document_path,
    legacy_origin,
    selector,
    list_only,
    interactive,
    mode,
    preferred_release_id,
) = sys.argv[1:]


def fail(message):
    print(f"clive: {message}", file=sys.stderr)
    raise SystemExit(2)


def valid_text(value):
    return (
        isinstance(value, str)
        and bool(value.strip())
        and not any(ord(character) < 32 or ord(character) == 127 for character in value)
    )


class RejectRedirects(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, request, fp, code, message, headers, new_url):
        raise urllib.error.HTTPError(
            request.full_url,
            code,
            "global catalog redirect refused",
            headers,
            fp,
        )


opener = urllib.request.build_opener(
    urllib.request.ProxyHandler({}), RejectRedirects()
)


def fetch_catalog(origin):
    request = urllib.request.Request(origin + "/v1/models", method="GET")
    with opener.open(request, timeout=5) as response:
        if response.status < 200 or response.status >= 300:
            raise OSError(f"HTTP {response.status}")
        return json.loads(response.read())


def validate_catalog_item(item, *, expected=None):
    if not isinstance(item, dict) or not valid_text(item.get("id")):
        fail("global catalog contains an invalid release id")
    release_id = item["id"]
    metadata = item.get("ambix")
    if metadata is None and expected is not None:
        # The engine carries no site metadata. That is not a fault: the block
        # is launch-owned data echoed back through a middleware only some
        # engines accept, and the endpoint document beside us already carries
        # the same values from the serve's own registration. Requiring the
        # engine to repeat them made this launcher refuse a healthy endpoint.
        family = expected["accelerator_family"]
        count = expected["accelerator_count"]
        precision = expected["checkpoint_precision"]
    elif not isinstance(metadata, dict):
        fail(f"release {release_id!r} has no ambix metadata")
    else:
        family = metadata.get("accelerator_family")
        count = metadata.get("accelerator_count")
        precision = metadata.get("checkpoint_precision")
    if not valid_text(family):
        fail(f"release {release_id!r} has an invalid accelerator family")
    if type(count) is not int or count not in {2, 4, 6, 8}:
        fail(f"release {release_id!r} has an invalid accelerator count")
    if not valid_text(precision):
        fail(f"release {release_id!r} has an invalid checkpoint precision")
    max_context = item.get("max_model_len")
    if max_context is not None and (
        type(max_context) is not int or max_context <= 0
    ):
        fail(f"release {release_id!r} has an invalid maximum context")
    if metadata is not None and expected is not None and (
        release_id != expected["model_id"]
        or family != expected["accelerator_family"]
        or count != expected["accelerator_count"]
        or precision != expected["checkpoint_precision"]
        or max_context != expected["max_context"]
    ):
        raise ValueError("engine catalog disagrees with endpoint document")
    return release_id, family, count, precision, max_context


def launcher_item(entry, *, catalog_item=None):
    if not isinstance(entry, dict):
        fail("endpoint document contains an invalid entry")
    required = {
        "model_id",
        "host",
        "port",
        "accelerator_family",
        "accelerator_count",
        "checkpoint_precision",
        "max_context",
    }
    if set(entry) != required:
        fail("endpoint document contains an incomplete entry")
    host = entry.get("host")
    port = entry.get("port")
    if (
        not valid_text(host)
        or any(character.isspace() or character in "/?#@" for character in host)
        or type(port) is not int
        or not 1 <= port <= 65535
    ):
        fail("endpoint document contains an invalid origin")
    release_id = entry.get("model_id")
    family = entry.get("accelerator_family")
    count = entry.get("accelerator_count")
    precision = entry.get("checkpoint_precision")
    max_context = entry.get("max_context")
    if not valid_text(release_id):
        fail("endpoint document contains an invalid release id")
    if not valid_text(family):
        fail(f"release {release_id!r} has an invalid accelerator family")
    if type(count) is not int or count not in {2, 4, 6, 8}:
        fail(f"release {release_id!r} has an invalid accelerator count")
    if not valid_text(precision):
        fail(f"release {release_id!r} has an invalid checkpoint precision")
    if type(max_context) is not int or max_context <= 0:
        fail(f"release {release_id!r} has an invalid maximum context")
    if catalog_item is not None:
        validate_catalog_item(catalog_item, expected=entry)
    origin = f"http://{host}:{port}"
    topology_selector = f"{release_id}@{count}x{family.lower()}"
    label = f"{release_id} · {count}×{family} · {precision}"
    label += f" · {max_context // 1024}k ctx"
    return {
        "id": release_id,
        "origin": origin,
        "family": family,
        "count": count,
        "precision": precision,
        "max_context": max_context,
        "selector": topology_selector,
        "label": label,
    }


items = []
release_ids = set()
catalogs_by_origin = {}
routing_origins = []


def cached_catalog(origin):
    if origin not in catalogs_by_origin:
        catalogs_by_origin[origin] = fetch_catalog(origin)
    return catalogs_by_origin[origin]


def catalog_match(catalog, entry):
    if not isinstance(catalog, dict) or not isinstance(catalog.get("data"), list):
        return None
    matches = [
        item
        for item in catalog["data"]
        if isinstance(item, dict) and item.get("id") == entry["model_id"]
    ]
    if len(matches) != 1:
        return None
    match = matches[0]
    metadata = match.get("ambix")
    if match.get("max_model_len") != entry["max_context"]:
        return None
    # Absence is accepted; disagreement is not. A card that states a topology
    # different from the document describes a different serve.
    if metadata is not None and (
        not isinstance(metadata, dict)
        or metadata.get("accelerator_family") != entry["accelerator_family"]
        or metadata.get("accelerator_count") != entry["accelerator_count"]
        or metadata.get("checkpoint_precision") != entry["checkpoint_precision"]
    ):
        return None
    return match


if legacy_origin:
    try:
        payload = cached_catalog(legacy_origin)
    except (OSError, urllib.error.URLError) as error:
        fail(f"global catalog is unreachable: {error}")
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        fail(f"global catalog is malformed: {error}")
    if not isinstance(payload, dict) or not isinstance(payload.get("data"), list):
        fail("global catalog must contain a model data list")
    if not payload["data"]:
        fail("global catalog contains no models")
    # Topology comes from the site-owned endpoint document, and the catalog is
    # read for liveness. An engine that cannot echo the site metadata back
    # through its own card -- SGLang takes no middleware -- would otherwise be
    # rejected here even while serving, which is the same refusal the router
    # and the publisher stopped making. Best effort: if the document cannot be
    # read, a card carrying its own block still validates on its own.
    document_topology = {}
    try:
        with open(document_path, encoding="utf-8") as _doc:
            _payload = json.load(_doc)
        for _entry in _payload.get("endpoints") or []:
            if isinstance(_entry, dict) and valid_text(_entry.get("model_id")):
                document_topology[_entry["model_id"]] = _entry
    except (OSError, UnicodeDecodeError, json.JSONDecodeError):
        document_topology = {}

    for catalog_item in payload["data"]:
        _expected = None
        if isinstance(catalog_item, dict) and catalog_item.get("ambix") is None:
            _expected = document_topology.get(catalog_item.get("id"))
            if _expected is None:
                fail(
                    f"release {catalog_item.get('id')!r} states no topology and the "
                    "endpoint document carries none for it"
                )
        release_id, family, count, precision, max_context = validate_catalog_item(
            catalog_item, expected=_expected
        )
        if release_id in release_ids:
            fail(f"global catalog repeats release id {release_id!r}")
        release_ids.add(release_id)
        topology_selector = f"{release_id}@{count}x{family.lower()}"
        label = f"{release_id} · {count}×{family} · {precision}"
        if max_context is not None:
            label += f" · {max_context // 1024}k ctx"
        items.append(
            {
                "id": release_id,
                "origin": legacy_origin,
                "family": family,
                "count": count,
                "precision": precision,
                "max_context": max_context,
                "selector": topology_selector,
                "label": label,
            }
        )
else:
    try:
        with open(document_path, encoding="utf-8") as document:
            payload = json.load(document)
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as error:
        fail(f"endpoint document is unreadable: {error}")
    if not isinstance(payload, dict) or not isinstance(payload.get("endpoints"), list):
        fail("endpoint document must contain an endpoints list")
    if not payload["endpoints"]:
        fail("endpoint document contains no endpoints")
    published_routing_origins = payload.get("routing_origins", [])
    if not isinstance(published_routing_origins, list):
        fail("endpoint document contains an invalid routing origins list")
    for published_origin in published_routing_origins:
        if not isinstance(published_origin, dict) or set(published_origin) != {
            "host",
            "port",
        }:
            fail("endpoint document contains an invalid routing origin")
        host = published_origin.get("host")
        port = published_origin.get("port")
        if (
            not valid_text(host)
            or any(character.isspace() or character in "/?#@" for character in host)
            or type(port) is not int
            or not 1 <= port <= 65535
        ):
            fail("endpoint document contains an invalid routing origin")
        origin = f"http://{host}:{port}"
        if origin not in routing_origins:
            routing_origins.append(origin)
    entries = payload["endpoints"]
    for entry in entries:
        candidate = launcher_item(entry)
        if candidate["id"] in release_ids:
            fail(f"endpoint document repeats release id {candidate['id']!r}")
        release_ids.add(candidate["id"])
    for entry in entries:
        origin = f'http://{entry["host"]}:{entry["port"]}'
        try:
            catalog = cached_catalog(origin)
            match = catalog_match(catalog, entry)
            if match is None:
                continue
            items.append(launcher_item(entry, catalog_item=match))
        except (
            OSError,
            TypeError,
            ValueError,
            UnicodeDecodeError,
            json.JSONDecodeError,
            urllib.error.URLError,
        ):
            continue
    if not items:
        fail("endpoint discovery contains no reachable models")

    for origin in routing_origins:
        try:
            cached_catalog(origin)
        except (
            OSError,
            UnicodeDecodeError,
            json.JSONDecodeError,
            urllib.error.URLError,
        ):
            continue

if list_only == "true":
    for item in items:
        print(f'{item["selector"]}\t{item["label"]}')
    raise SystemExit(0)

primary_local = items[0]
secondary_local = items[1] if len(items) > 1 else primary_local

chosen = None
if selector:
    matches = [
        item
        for item in items
        if selector == item["id"] or selector.lower() == item["selector"].lower()
    ]
    if len(matches) != 1:
        available = ", ".join(item["selector"] for item in items)
        fail(f"selector {selector!r} did not identify one model; available: {available}")
    chosen = matches[0]
elif preferred_release_id:
    preferred_matches = [
        item for item in items if item["id"] == preferred_release_id
    ]
    if len(preferred_matches) == 1:
        chosen = preferred_matches[0]

if chosen is None and len(items) == 1:
    chosen = items[0]
elif chosen is None and interactive == "true":
    print("Clive global models:", file=sys.stderr)
    for index, item in enumerate(items, 1):
        print(f"  {index}) {item['label']}", file=sys.stderr)
    print("Select model: ", end="", file=sys.stderr, flush=True)
    with os.fdopen(3) as terminal_input:
        answer = terminal_input.readline().strip()
    try:
        choice = int(answer)
    except ValueError:
        fail("invalid model selection")
    if not 1 <= choice <= len(items):
        fail(f"model selection must be an integer from 1 through {len(items)}")
    chosen = items[choice - 1]
elif chosen is None:
    available = ", ".join(item["selector"] for item in items)
    fail(f"multiple models are available; use --selector ({available})")


def origin_releases(origin):
    catalog = catalogs_by_origin.get(origin)
    if catalog is None:
        return set()
    if legacy_origin:
        catalog_ids = {
            item.get("id") for item in catalog.get("data", []) if isinstance(item, dict)
        }
        return {item["id"] for item in items if item["id"] in catalog_ids}
    entries_by_id = {entry["model_id"]: entry for entry in entries}
    return {
        item["id"]
        for item in items
        if catalog_match(catalog, entries_by_id[item["id"]]) is not None
    }


listed_releases = {item["id"] for item in items}
candidate_origins = routing_origins + [item["origin"] for item in items]
harness_origin = chosen["origin"]
for origin in dict.fromkeys(candidate_origins):
    if origin_releases(origin) == listed_releases:
        harness_origin = origin
        break
reachable_releases = origin_releases(harness_origin)
picker_settings = {
    "modelPicker": {
        "options": [
            {
                "model": item["id"],
                "label": item["id"],
                # Map the served id onto a model the harness's catalog knows.
                # Without it the harness reports the release as undescribed and
                # falls back to an assumed context window; the launcher already
                # exports the real window, so this silences a warning rather
                # than changing behaviour -- but an undescribed model is also
                # one whose capabilities the harness has to guess, and a
                # warning printed on every healthy run is one nobody reads when
                # it finally means something.
                "behavesAs": "claude-sonnet-5",
                "description": (
                    f'{item["count"]}×{item["family"]} · '
                    f'{item["precision"]} · '
                    f'{item["max_context"] // 1024}k context'
                    if item["max_context"] is not None
                    else (
                        f'{item["count"]}×{item["family"]} · '
                        f'{item["precision"]} · context not reported'
                    )
                ),
            }
            for item in items
            if item["id"] in reachable_releases
        ],
        "replaceBuiltInOptions": mode == "local",
    }
}

print(chosen["id"])
print(harness_origin)
print(chosen["max_context"] or "")
print(chosen["family"])
print(chosen["count"])
print(chosen["precision"])
print(json.dumps(picker_settings, ensure_ascii=False, separators=(",", ":")))


def exact_context(item):
    return (
        f'{item["max_context"]:,}-token engine-reported context'
        if item["max_context"] is not None
        else "engine-reported context unavailable"
    )


def alias_description(item):
    context = (
        f'{item["max_context"] // 1024}k ctx'
        if item["max_context"] is not None
        else "unknown ctx"
    )
    return f'{item["count"]}×{item["family"]} · {item["precision"]}, {context}'


if mode == "hybrid":
    guidance = (
        "Clive dispatch guidance: the sonnet alias is the primary local worker "
        f'and resolves to {primary_local["id"]} '
        f'({primary_local["count"]}×{primary_local["family"]}, '
        f'{exact_context(primary_local)}). The haiku alias is the secondary '
        f'local worker and resolves to {secondary_local["id"]} '
        f'({secondary_local["count"]}×{secondary_local["family"]}, '
        f'{exact_context(secondary_local)}). Send bulk, parallel, and mechanical '
        "work to sonnet. Keep adjudication and physics-critical judgement on "
        "the opus or fable frontier slots."
    )
else:
    guidance = (
        "Clive dispatch guidance: the sonnet alias is the primary local worker "
        f'and resolves to {chosen["id"]} '
        f'({chosen["count"]}×{chosen["family"]}, {exact_context(chosen)}). '
        "Send bulk, parallel, and mechanical work to sonnet. Keep adjudication "
        "and physics-critical judgement on a frontier slot when one is available; "
        "local-only mode does not provide a frontier slot."
    )

print(guidance)
print(primary_local["id"])
print(alias_description(primary_local))
print(secondary_local["id"])
print(alias_description(secondary_local))
PY
)"; then
    :
else
    exit $?
fi

if $LIST_ONLY; then
    printf '%s\n' "$_CATALOG_RESULT"
    exit 0
fi

mapfile -t _CATALOG_FIELDS <<< "$_CATALOG_RESULT"
if [[ "${#_CATALOG_FIELDS[@]}" -ne 12 ]]; then
    echo "clive: catalog selection returned invalid data." >&2
    exit 2
fi
MODEL_ID="${_CATALOG_FIELDS[0]}"
GLOBAL_ORIGIN="${_CATALOG_FIELDS[1]}"
MAX_CONTEXT="${_CATALOG_FIELDS[2]}"
ACCELERATOR_FAMILY="${_CATALOG_FIELDS[3]}"
ACCELERATOR_COUNT="${_CATALOG_FIELDS[4]}"
CHECKPOINT_PRECISION="${_CATALOG_FIELDS[5]}"
PICKER_SETTINGS="${_CATALOG_FIELDS[6]}"
DISPATCH_GUIDANCE="${_CATALOG_FIELDS[7]}"
PRIMARY_LOCAL_MODEL="${_CATALOG_FIELDS[8]}"
PRIMARY_LOCAL_DESCRIPTION="${_CATALOG_FIELDS[9]}"
SECONDARY_LOCAL_MODEL="${_CATALOG_FIELDS[10]}"
SECONDARY_LOCAL_DESCRIPTION="${_CATALOG_FIELDS[11]}"
RUNTIME_LABEL="${ACCELERATOR_COUNT}×${ACCELERATOR_FAMILY} · ${CHECKPOINT_PRECISION}"
CONTEXT_LABEL="unknown"
if [[ -n "$MAX_CONTEXT" ]]; then
    if (( MAX_CONTEXT < 2 )); then
        echo "clive: selected release '$MODEL_ID' has too little context for a prompt and response." >&2
        exit 2
    fi
    # Keep the harness default for large windows. Smaller windows reserve at
    # most one quarter for a response so prompt and tool history retain room.
    OUTPUT_RESERVATION=$(( MAX_CONTEXT / 4 ))
    if (( OUTPUT_RESERVATION > 32000 )); then
        OUTPUT_RESERVATION=32000
    elif (( OUTPUT_RESERVATION < 1 )); then
        OUTPUT_RESERVATION=1
    fi
    export CLAUDE_CODE_MAX_OUTPUT_TOKENS="$OUTPUT_RESERVATION"
    USABLE_INPUT_BUDGET=$(( MAX_CONTEXT - OUTPUT_RESERVATION ))
    # The engine bounds prompt plus requested output by the served window, so
    # the harness must be told the input ceiling, not the whole window. Given
    # the whole window it would fill toward it and every request would then ask
    # for prompt plus the reservation on top and be refused at the API. Telling
    # it the ceiling turns that refusal into context pressure it can compact.
    export CLAUDE_CODE_MAX_CONTEXT_TOKENS="$USABLE_INPUT_BUDGET"
    # Auto-compaction is governed by its own window, separate from the input
    # ceiling above, and the harness reads it ahead of the behavesAs default.
    # Cap it at the lane ceiling so a large-window release compacts near the
    # usable budget rather than at the 200k Sonnet-class default, while a
    # smaller release still compacts at its own budget.
    AUTO_COMPACT_WINDOW_CEILING=__AUTO_COMPACT_WINDOW_CEILING__
    if (( USABLE_INPUT_BUDGET < AUTO_COMPACT_WINDOW_CEILING )); then
        export CLAUDE_CODE_AUTO_COMPACT_WINDOW="$USABLE_INPUT_BUDGET"
    else
        export CLAUDE_CODE_AUTO_COMPACT_WINDOW="$AUTO_COMPACT_WINDOW_CEILING"
    fi
    CONTEXT_LABEL="$(( MAX_CONTEXT / 1024 ))k"
else
    unset CLAUDE_CODE_MAX_CONTEXT_TOKENS
    unset CLAUDE_CODE_MAX_OUTPUT_TOKENS
    unset CLAUDE_CODE_AUTO_COMPACT_WINDOW
fi

PROFILE_SETTINGS="$PICKER_SETTINGS"
PROFILE_PROMPT="$DISPATCH_GUIDANCE"
PROFILE_ARGS=()
PROFILE_RECEIPT=""
PROFILE_ROUTE="none"
PROFILE_TOOLS=""
if [[ -n "$WORKER_PROFILE" ]]; then
    [[ "$HARNESS" == "claude" ]] || {
        echo "clive: --worker-profile is supported only with the Claude harness." >&2
        exit 2
    }
    USER_SETTINGS="${CLIVE_USER_SETTINGS:-${HOME}/.claude/settings.json}"
    PROFILE_DATA="$(python3 - "$WORKER_PROFILE" "$PWD" "$USER_SETTINGS" "$PICKER_SETTINGS" "$DISPATCH_GUIDANCE" <<'PY'
import hashlib
import json
import os
import sys
from pathlib import Path


def fail(message):
    print(f"clive: invalid worker profile: {message}", file=sys.stderr)
    raise SystemExit(2)


def resolve_file(value, field, *, required=True):
    if value is None and not required:
        return None
    if not isinstance(value, str) or not value.strip():
        fail(f"{field} must be a path")
    path = Path(value).expanduser()
    if not path.is_absolute():
        path = Path.cwd() / path
    if not path.is_file():
        fail(f"{field} does not exist: {path}")
    return path.resolve()


def digest(path):
    if path is None:
        return None
    hasher = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            hasher.update(block)
    return {"path": str(path), "sha256": hasher.hexdigest()}


profile_path = resolve_file(sys.argv[1], "profile")
try:
    with profile_path.open(encoding="utf-8") as stream:
        profile = json.load(stream)
except (UnicodeDecodeError, json.JSONDecodeError) as error:
    fail(f"profile is not valid JSON: {error}")
if not isinstance(profile, dict):
    fail("profile must be a JSON object")
if set(profile) != {"digest", "mcp_config", "tools"}:
    fail("profile must contain exactly digest, mcp_config and tools")

digest_path = resolve_file(profile["digest"], "digest")
mcp_path = resolve_file(profile["mcp_config"], "mcp_config", required=False)
tools = profile["tools"]
if (
    not isinstance(tools, list)
    or not tools
    or any(not isinstance(tool, str) or not tool.strip() for tool in tools)
):
    fail("tools must be a non-empty list of names")
tools_value = ",".join(tools)

working_agents = Path(sys.argv[2]) / "AGENTS.md"
agents_path = working_agents.resolve() if working_agents.is_file() else None
try:
    with Path(sys.argv[3]).open(encoding="utf-8") as stream:
        user_settings = json.load(stream)
except FileNotFoundError:
    user_settings = {}
except (OSError, UnicodeDecodeError, json.JSONDecodeError) as error:
    fail(f"user settings are unreadable: {error}")
if not isinstance(user_settings, dict):
    fail("user settings must be a JSON object")
hooks = user_settings.get("hooks", {})
if not isinstance(hooks, dict):
    fail("user settings hooks must be an object")

hook_commands = []


def collect_commands(value):
    if isinstance(value, dict):
        command = value.get("command")
        if isinstance(command, str) and command:
            hook_commands.append(command)
        for nested in value.values():
            collect_commands(nested)
    elif isinstance(value, list):
        for nested in value:
            collect_commands(nested)


collect_commands(hooks)
settings = json.loads(sys.argv[4])
if not isinstance(settings, dict):
    fail("launcher settings are not an object")
settings["hooks"] = hooks

prompt_parts = [
    "Role digest (loaded from the worker profile):\n" + digest_path.read_text(encoding="utf-8")
]
if agents_path is not None:
    prompt_parts.append(
        "Repository guidance (loaded from the working directory):\n"
        + agents_path.read_text(encoding="utf-8")
    )
prompt_parts.append("Dispatch guidance:\n" + sys.argv[5])
prompt = "\n\n".join(prompt_parts)

# Claude's help states that --bare skips settings hooks. Preserve the worker
# safety hooks by taking the explicit settings route whenever the profile has
# any hook commands; a profile without hooks can use the smaller bare route.
route = "settings" if hook_commands else "bare"
added_args = []
if route == "bare":
    added_args.append("--bare")
else:
    added_args.extend(("--setting-sources", "user"))
added_args.extend(("--append-system-prompt", prompt))
if mcp_path is not None:
    added_args.extend(("--strict-mcp-config", "--mcp-config", str(mcp_path)))
added_args.extend(("--tools", tools_value))

receipt = {
    "profile": str(profile_path),
    "route": route,
    "files": {
        "profile": digest(profile_path),
        "digest": digest(digest_path),
        "mcp_config": digest(mcp_path),
        "agents": digest(agents_path),
        "settings": digest(Path(sys.argv[3])) if Path(sys.argv[3]).is_file() else None,
    },
    "tools": tools,
    "hooks": hook_commands,
    "added_arguments": added_args,
}
print(json.dumps({
    "settings": settings,
    "prompt": prompt,
    "tools": tools_value,
    "route": route,
    "receipt": receipt,
}, ensure_ascii=False, separators=(",", ":")))
PY
)"
    PROFILE_SETTINGS="$(python3 -c 'import json,sys; print(json.dumps(json.load(sys.stdin)["settings"], ensure_ascii=False, separators=(",", ":")), end="")' <<< "$PROFILE_DATA")"
    PROFILE_PROMPT="$(python3 -c 'import json,sys; print(json.load(sys.stdin)["prompt"], end="")' <<< "$PROFILE_DATA")"
    PROFILE_TOOLS="$(python3 -c 'import json,sys; print(json.load(sys.stdin)["tools"], end="")' <<< "$PROFILE_DATA")"
    PROFILE_ROUTE="$(python3 -c 'import json,sys; print(json.load(sys.stdin)["route"], end="")' <<< "$PROFILE_DATA")"
    if [[ "$PROFILE_ROUTE" == "bare" ]]; then
        PROFILE_ARGS+=(--bare)
    else
        PROFILE_ARGS+=(--setting-sources user)
    fi
    PROFILE_ARGS+=(--append-system-prompt "$PROFILE_PROMPT")
    MCP_ARGUMENTS="$(python3 -c 'import json,sys; d=json.load(sys.stdin); f=d["receipt"]["files"]["mcp_config"]; print(f["path"] if f else "", end="")' <<< "$PROFILE_DATA")"
    if [[ -n "$MCP_ARGUMENTS" ]]; then
        PROFILE_ARGS+=(--strict-mcp-config --mcp-config "$MCP_ARGUMENTS")
    fi
    PROFILE_ARGS+=(--tools "$PROFILE_TOOLS")
    PROFILE_RECEIPT="$(python3 -c 'import json,sys; print(json.dumps(json.load(sys.stdin)["receipt"], ensure_ascii=False, separators=(",", ":")), end="")' <<< "$PROFILE_DATA")"
    if [[ -n "${CLIVE_PROFILE_RECEIPT:-}" ]]; then
        printf '%s\n' "$PROFILE_RECEIPT" >> "$CLIVE_PROFILE_RECEIPT"
    else
        printf '%s\n' "$PROFILE_RECEIPT" >&2
    fi
fi

# The global service is anonymous. Harnesses receive a fixed non-secret value
# only because their client configuration requires an API-key variable.
KEY="clive-no-auth"
SUPPORTED_CAPABILITIES="thinking"
if [[ "$WORKER_PROFILE" && "$PROFILE_ROUTE" == "bare" ]]; then
    # Bare mode does not read the auth-token variable; its documented
    # credential path is the API-key variable or apiKeyHelper in settings.
    export ANTHROPIC_API_KEY="$KEY"
    unset ANTHROPIC_AUTH_TOKEN
fi

if [[ "$HARNESS" == "codex" ]]; then
    command -v codex >/dev/null 2>&1 || { echo "clive: 'codex' not on PATH." >&2; exit 127; }
    OPENAI_BASE_URL="${GLOBAL_ORIGIN}/v1" OPENAI_API_KEY="$KEY" exec codex --model "$MODEL_ID" "${ARGS[@]}"
fi

command -v claude >/dev/null 2>&1 || { echo "clive: 'claude' not on PATH." >&2; exit 127; }

if [[ "$MODE" == "local" ]]; then
    export ANTHROPIC_BASE_URL="$GLOBAL_ORIGIN"
    export ANTHROPIC_AUTH_TOKEN="$KEY"
    if [[ "$WORKER_PROFILE" && "$PROFILE_ROUTE" == "bare" ]]; then
        export ANTHROPIC_API_KEY="$KEY"
        unset ANTHROPIC_AUTH_TOKEN
    else
        export ANTHROPIC_API_KEY=""
    fi
    export ANTHROPIC_DEFAULT_OPUS_MODEL="$MODEL_ID"
    export ANTHROPIC_DEFAULT_OPUS_MODEL_NAME="$MODEL_ID"
    export ANTHROPIC_DEFAULT_OPUS_MODEL_DESCRIPTION="$RUNTIME_LABEL, $CONTEXT_LABEL ctx"
    export ANTHROPIC_DEFAULT_OPUS_MODEL_SUPPORTED_CAPABILITIES="$SUPPORTED_CAPABILITIES"
    export ANTHROPIC_DEFAULT_SONNET_MODEL="$MODEL_ID"
    export ANTHROPIC_DEFAULT_SONNET_MODEL_NAME="$MODEL_ID"
    export ANTHROPIC_DEFAULT_SONNET_MODEL_DESCRIPTION="$RUNTIME_LABEL, $CONTEXT_LABEL ctx"
    export ANTHROPIC_DEFAULT_SONNET_MODEL_SUPPORTED_CAPABILITIES="$SUPPORTED_CAPABILITIES"
    export ANTHROPIC_DEFAULT_HAIKU_MODEL="$MODEL_ID"
    export ANTHROPIC_DEFAULT_HAIKU_MODEL_NAME="$MODEL_ID"
    export ANTHROPIC_DEFAULT_HAIKU_MODEL_DESCRIPTION="$RUNTIME_LABEL, $CONTEXT_LABEL ctx"
    export ANTHROPIC_DEFAULT_HAIKU_MODEL_SUPPORTED_CAPABILITIES="$SUPPORTED_CAPABILITIES"
    export ANTHROPIC_DEFAULT_FABLE_MODEL="$MODEL_ID"
    export ANTHROPIC_DEFAULT_FABLE_MODEL_NAME="$MODEL_ID"
    export ANTHROPIC_DEFAULT_FABLE_MODEL_DESCRIPTION="$RUNTIME_LABEL, $CONTEXT_LABEL ctx"
    export ANTHROPIC_DEFAULT_FABLE_MODEL_SUPPORTED_CAPABILITIES="$SUPPORTED_CAPABILITIES"
    export ANTHROPIC_SMALL_FAST_MODEL="$MODEL_ID"
    export ANTHROPIC_MODEL="$MODEL_ID"
    export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1
    if [[ -n "$WORKER_PROFILE" ]]; then
        exec claude "${PROFILE_ARGS[@]}" --settings "$PROFILE_SETTINGS" "${ARGS[@]}"
    else
        exec claude --settings "$PICKER_SETTINGS" --append-system-prompt "$DISPATCH_GUIDANCE" "${ARGS[@]}"
    fi
fi

__HYBRID_BRANCH__
"""
    hybrid_branch = r"""# Hosted providers are reached only by explicit hybrid selection after global catalog selection.
if [[ -z "$OPENROUTER_NATIVE_RELEASE" ]]; then
    echo "clive: hybrid mode is not installed; redeploy with 'imas-ambix agent clive PROFILE --mode hybrid'." >&2
    exit 2
fi
if [[ "$MODEL_ID" != "$OPENROUTER_NATIVE_RELEASE" ]]; then
    echo "clive: selected native release '$MODEL_ID' is not configured in the OpenRouter proxy (configured: '$OPENROUTER_NATIVE_RELEASE'); redeploy the proxy for that release." >&2
    exit 2
fi
if ! systemctl --user is-active --quiet "$LITELLM_SERVICE" 2>/dev/null; then
    echo "clive: starting $LITELLM_SERVICE ..." >&2
    if ! systemctl --user start "$LITELLM_SERVICE" 2>/dev/null; then
        echo "clive: could not start $LITELLM_SERVICE." >&2
        exit 1
    fi
fi

_PROXY_READY=false
for _attempt in $(seq 1 60); do
    (exec 3<>"/dev/tcp/127.0.0.1/$LITELLM_PORT") 2>/dev/null && { exec 3>&- 3<&-; _PROXY_READY=true; break; }
    sleep 0.5
done
if ! $_PROXY_READY; then
    echo "clive: $LITELLM_SERVICE did not become ready." >&2
    exit 1
fi

export ANTHROPIC_BASE_URL="http://127.0.0.1:$LITELLM_PORT"
export ANTHROPIC_AUTH_TOKEN="clive"
if [[ "$WORKER_PROFILE" && "$PROFILE_ROUTE" == "bare" ]]; then
    export ANTHROPIC_API_KEY="$KEY"
    unset ANTHROPIC_AUTH_TOKEN
else
    export ANTHROPIC_API_KEY=""
fi
export ANTHROPIC_MODEL="$MODEL_ID"
export ANTHROPIC_DEFAULT_SONNET_MODEL="$PRIMARY_LOCAL_MODEL"
export ANTHROPIC_DEFAULT_SONNET_MODEL_NAME="$PRIMARY_LOCAL_MODEL"
export ANTHROPIC_DEFAULT_SONNET_MODEL_DESCRIPTION="$PRIMARY_LOCAL_DESCRIPTION"
export ANTHROPIC_DEFAULT_SONNET_MODEL_SUPPORTED_CAPABILITIES="$SUPPORTED_CAPABILITIES"
export ANTHROPIC_DEFAULT_HAIKU_MODEL="$SECONDARY_LOCAL_MODEL"
export ANTHROPIC_DEFAULT_HAIKU_MODEL_NAME="$SECONDARY_LOCAL_MODEL"
export ANTHROPIC_DEFAULT_HAIKU_MODEL_DESCRIPTION="$SECONDARY_LOCAL_DESCRIPTION"
export ANTHROPIC_DEFAULT_HAIKU_MODEL_SUPPORTED_CAPABILITIES="$SUPPORTED_CAPABILITIES"
export ANTHROPIC_DEFAULT_OPUS_MODEL="or-opus-4.8"
export ANTHROPIC_DEFAULT_OPUS_MODEL_NAME="or-opus-4.8"
export ANTHROPIC_DEFAULT_OPUS_MODEL_DESCRIPTION="Claude Opus 4.8 via OpenRouter — frontier"
export ANTHROPIC_DEFAULT_OPUS_MODEL_SUPPORTED_CAPABILITIES="$SUPPORTED_CAPABILITIES"
export ANTHROPIC_DEFAULT_FABLE_MODEL="or-glm-5.2"
export ANTHROPIC_DEFAULT_FABLE_MODEL_NAME="or-glm-5.2"
export ANTHROPIC_DEFAULT_FABLE_MODEL_DESCRIPTION="GLM-5.2 via OpenRouter — open-weight frontier, 1M ctx"
export ANTHROPIC_DEFAULT_FABLE_MODEL_SUPPORTED_CAPABILITIES="$SUPPORTED_CAPABILITIES"
export ANTHROPIC_CUSTOM_MODEL_OPTION="or-gpt-5.5"
export ANTHROPIC_CUSTOM_MODEL_OPTION_NAME="or-gpt-5.5"
export ANTHROPIC_CUSTOM_MODEL_OPTION_DESCRIPTION="GPT-5.5 via OpenRouter — coding model"
export ANTHROPIC_CUSTOM_MODEL_OPTION_SUPPORTED_CAPABILITIES="$SUPPORTED_CAPABILITIES"
export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1
if [[ -n "$WORKER_PROFILE" ]]; then
    exec claude "${PROFILE_ARGS[@]}" --settings "$PROFILE_SETTINGS" "${ARGS[@]}"
else
    exec claude --settings "$PICKER_SETTINGS" --append-system-prompt "$DISPATCH_GUIDANCE" "${ARGS[@]}"
fi
"""
    local_branch = r"""echo "clive: hybrid mode is not installed; redeploy with 'imas-ambix agent clive PROFILE --mode hybrid'." >&2
exit 2
"""
    return (
        template.replace("__GLOBAL_ORIGIN__", shlex.quote(legacy_origin))
        .replace("__ENDPOINT_DOCUMENT__", shlex.quote(endpoint_document))
        .replace("__PREFERRED_RELEASE_ID__", shlex.quote(preferred_release_id))
        .replace("__OPENROUTER_NATIVE_RELEASE__", shlex.quote(proxy_native_release))
        .replace("__LITELLM_PORT__", str(LITELLM_PORT))
        .replace(
            "__AUTO_COMPACT_WINDOW_CEILING__", str(AUTO_COMPACT_WINDOW_CEILING)
        )
        .replace(
            "__HYBRID_BRANCH__",
            hybrid_branch if mode == "hybrid" else local_branch,
        )
    )
