# ruff: noqa: E501 — the module is mostly an embedded bash template; line length
# is governed by the generated shell script, not Python style.
"""Generator for the ``clive`` agent-CLI launcher.

``clive`` ("CLI + live") points an interactive agent harness — Claude Code or
the OpenAI Codex CLI — at the model served on the GPU node.  The vLLM server
exposes BOTH the Anthropic Messages API (``/v1/messages``) and the OpenAI API
(``/v1/chat/completions``) on one port, so the same server, key, and model
back either harness with full reasoning, tool calling, and prompt caching.

The script is **generated from** :class:`SiteConfig` so its endpoint, port,
default model, and key-file path never drift from what the server actually
serves — change the site config (or the served model) and re-deploy.  It is
otherwise standalone and dependency-free: the consumer needs only the script,
the shared key file, and the agent CLI on PATH — not this package.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from imas_ambix.agent.profile import SiteConfig


def generate_clive_script(site: SiteConfig, default_model: str) -> str:
    """Render the ``clive`` launcher for *site* defaulting to *default_model*.

    Parameters
    ----------
    site:
        Cluster configuration supplying the URL, key-file path, and group.
    default_model:
        ``served_name`` of the model clive targets by default (the profile
        the operator most recently serves / sets as default).
    """
    url = site.default_url
    key_file = str(site.api_key_file)
    return f'''#!/usr/bin/env bash
# clive — drive an agent CLI against the GPU-served local model.
#
# GENERATED by `imas-ambix agent clive --deploy`. Do not edit in place — edit
# the generator (imas_ambix/agent/clive.py) and re-deploy, or the next deploy
# overwrites your change. The endpoint/model/key-file below come from the
# ambix SiteConfig, so clive stays in lockstep with what the server serves.
#
# The vLLM server exposes BOTH the Anthropic Messages API (/v1/messages) and
# the OpenAI API (/v1/chat/completions) on the same port, so the same server,
# key, and model back either harness with full reasoning, tool calling, and
# prompt caching (vLLM automatic prefix caching; >0.17.1 handles Claude Code's
# per-request hash, so caching is not defeated).
#
# Usage:
#   clive [--claude|--codex] [--url URL] [--model NAME] [agent-args...]
#   clive "explain this repo"            # Claude Code (default)
#   clive --codex "write a test"         # OpenAI Codex CLI
#
# The API key is never placed on a command line: it is read from the shared
# key file into an env var the agent reads natively. Distribute access by
# storage-group membership, not by copying the key.

set -euo pipefail

# ── Defaults (generated from ambix SiteConfig; override via env or flags) ────
AMBIX_URL="${{AMBIX_AGENT_URL:-{url}}}"
# Model: empty → auto-detect from the live server's /v1/models at runtime, so
# clive tracks whatever is actually serving (swap the served model, no redeploy).
# Falls back to this profile's served_name if the query fails. Override via
# AMBIX_AGENT_MODEL or --model.
AMBIX_MODEL="${{AMBIX_AGENT_MODEL:-}}"
AMBIX_MODEL_FALLBACK="{default_model}"
AMBIX_KEY_FILE="${{AMBIX_AGENT_KEY_FILE:-{key_file}}}"
HARNESS="claude"

usage() {{
    cat >&2 <<'USAGE'
clive — drive an agent CLI against the GPU-served local model.

  clive [--claude|--codex] [--url URL] [--model NAME] [agent-args...]

  --claude        Use Claude Code via the Anthropic Messages API (default).
  --codex         Use the OpenAI Codex CLI via the OpenAI API.
  --url URL       Server base URL.
  --model NAME    Served model name.
  -h, --help      Show this help.

Anything after a `--`, or any unrecognised argument, is passed to the agent.
Env overrides: AMBIX_AGENT_URL, AMBIX_AGENT_MODEL, AMBIX_AGENT_KEY_FILE,
AMBIX_AGENT_API_KEY.
USAGE
}}

# ── Parse clive's own flags; pass everything else to the agent ───────────────
ARGS=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --claude) HARNESS="claude"; shift ;;
        --codex)  HARNESS="codex";  shift ;;
        --url)    AMBIX_URL="$2";   shift 2 ;;
        --model)  AMBIX_MODEL="$2"; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        --) shift; ARGS+=("$@"); break ;;
        *)  ARGS+=("$1"); shift ;;
    esac
done

# ── Resolve the API key (env > file) without echoing it ──────────────────────
# Returns the key, or empty if none is configured. A keyless ("no-auth") server
# ignores the token, but Claude Code still wants the var set to something — the
# caller substitutes a dummy when this is empty.
read_key() {{
    if [[ -n "${{AMBIX_AGENT_API_KEY:-}}" ]]; then
        printf '%s' "$AMBIX_AGENT_API_KEY"; return 0
    fi
    [[ -r "$AMBIX_KEY_FILE" ]] || return 0
    local line
    line="$(grep -E '^[[:space:]]*AMBIX_AGENT_API_KEY[[:space:]]*=' "$AMBIX_KEY_FILE" | tail -1)"
    [[ -n "$line" ]] || return 0
    line="${{line#*=}}"
    line="${{line%\\"}}"; line="${{line#\\"}}"
    line="${{line%\\'}}"; line="${{line#\\'}}"
    printf '%s' "$line"
}}

KEY="$(read_key)"
# Keyless server: Claude Code/Codex still require a non-empty token; the server
# ignores it. Use a placeholder so the harness launches.
[[ -n "$KEY" ]] || KEY="no-auth"

# ── Check the endpoint is reachable (direct route; no SSH tunnel) ────────────
# The login and standard compute nodes route DIRECTLY to the GPU node's serve
# port (verified 2026-06-25: login -> 98dci4-gpu-0003:18800/health = 200). SSH
# -L port-forwarding to the compute node is administratively prohibited, so we
# do NOT tunnel — we use the direct URL and just warn if it isn't reachable.
check_reachable() {{
    local rest host port
    rest="${{AMBIX_URL#*://}}"
    host="${{rest%%[:/]*}}"
    port="${{rest##*:}}"; port="${{port%%/*}}"
    [[ "$port" == "$host" || -z "$port" ]] && port=80
    if (exec 3<>"/dev/tcp/$host/$port") 2>/dev/null; then
        exec 3>&- 3<&-
        return 0
    fi
    echo "clive: warning: $host:$port not reachable from here." >&2
    echo "       The serve job may be down (check: imas-ambix agent status)," >&2
    echo "       or this host has no route to the GPU node. Proceeding anyway." >&2
    return 0
}}

check_reachable

# ── Resolve the served model from /v1/models (unless overridden) ─────────────
# Query the live endpoint so clive uses whatever is actually serving. No jq
# dependency — extract the first "id" with grep/sed. Fall back to the baked-in
# served_name if the query fails (server down, no curl, etc.).
if [[ -z "$AMBIX_MODEL" ]]; then
    _models_json="$(curl -s --max-time 5 -H "Authorization: Bearer $KEY" \\
        "$AMBIX_URL/v1/models" 2>/dev/null || true)"
    AMBIX_MODEL="$(printf '%s' "$_models_json" \\
        | grep -oE '"id"[[:space:]]*:[[:space:]]*"[^"]+"' | head -1 \\
        | sed -E 's/.*"id"[[:space:]]*:[[:space:]]*"([^"]+)".*/\\1/')"
    if [[ -z "$AMBIX_MODEL" ]]; then
        AMBIX_MODEL="$AMBIX_MODEL_FALLBACK"
        echo "clive: could not query /v1/models; using fallback model '$AMBIX_MODEL'." >&2
    else
        printf "\nClive Code — Claude Unplugged\n\n" >&2
    fi
fi

# ── Launch the chosen harness ────────────────────────────────────────────────
case "$HARNESS" in
    claude)
        if ! command -v claude >/dev/null 2>&1; then
            echo "clive: 'claude' (Claude Code) not on PATH — install it per-user:" >&2
            echo "       https://docs.claude.com/en/docs/claude-code/setup" >&2
            exit 127
        fi
        # Claude Code speaks the Anthropic Messages API → vLLM /v1/messages.
        # Pin every tier to the one local model; blank ANTHROPIC_API_KEY so the
        # AUTH_TOKEN (Bearer) path is used, matching the server's --api-key.
        ANTHROPIC_BASE_URL="$AMBIX_URL" \\
        ANTHROPIC_AUTH_TOKEN="$KEY" \\
        ANTHROPIC_API_KEY="" \\
        ANTHROPIC_DEFAULT_OPUS_MODEL="$AMBIX_MODEL" \\
        ANTHROPIC_DEFAULT_SONNET_MODEL="$AMBIX_MODEL" \\
        ANTHROPIC_DEFAULT_HAIKU_MODEL="$AMBIX_MODEL" \\
        ANTHROPIC_MODEL="$AMBIX_MODEL" \\
        CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1 \\
        exec claude "${{ARGS[@]}}"
        ;;
    codex)
        if ! command -v codex >/dev/null 2>&1; then
            echo "clive: 'codex' (Codex CLI) not on PATH — install it per-user:" >&2
            echo "       npm install -g @openai/codex   (needs Node >= 18)" >&2
            exit 127
        fi
        # Codex speaks the OpenAI API → vLLM /v1/chat/completions, same port.
        OPENAI_BASE_URL="${{AMBIX_URL%/}}/v1" \\
        OPENAI_API_KEY="$KEY" \\
        exec codex --model "$AMBIX_MODEL" "${{ARGS[@]}}"
        ;;
    *)
        echo "clive: unknown harness '$HARNESS'" >&2; exit 2 ;;
esac
'''
