"""Generator for the ``orclive`` LiteLLM routing config.

``orclive`` runs a per-user LiteLLM proxy that lets one Claude Code session
route different tiers to different backends: the bulk tiers (sonnet, haiku) to
the **local** H200 model, and the heavy opus tier to **OpenRouter**. The proxy
needs a YAML config; this module generates it from :class:`SiteConfig` — the
same source-of-truth pattern as ``clive`` — so the local endpoint and served
model never drift, and the file is synced repo → ``/work`` on ``--deploy``.

The config is **secret-free**: the OpenRouter key is referenced as
``os.environ/OPENROUTER_API_KEY`` and supplied by ``orclive`` at proxy launch
from the per-user ``~/.config/openrouter/key``. Edit routing by editing this
generator (the YAML below) and re-deploying — do not hand-edit the ``/work``
copy.

Claude Code requests tier model names ``ambix-{{sonnet,haiku,opus}}`` (set by
``orclive`` via ``ANTHROPIC_DEFAULT_*_MODEL``); LiteLLM maps each to its backend.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from imas_ambix.agent.profile import SiteConfig


def generate_litellm_config(site: SiteConfig, local_model: str) -> str:
    """Render the orclive LiteLLM routing YAML for *site*.

    Two-entry router: ``local`` → the H200 model named by *local_model*,
    ``opus`` → OpenRouter.  ``model_info.description`` carries the actual
    served model name so proxy metadata queries see it.

    Set your session model with ``/model local`` (default) or ``/model opus``
    to switch — no env var clutter needed.

    Parameters
    ----------
    site:
        Cluster config — supplies the local endpoint URL.
    local_model:
        ``served_name`` of the local model (e.g. ``deepseek-v4-flash``).
    """
    local_url = site.default_url
    return f"""# imas-ambix — orclive LiteLLM routing config.
#
# GENERATED by `imas-ambix agent clive --deploy` from SiteConfig. Do NOT
# hand-edit the deployed /work copy — edit the generator
# (imas_ambix/agent/litellm_config.py) and re-deploy.
#
# SECRET-FREE: OpenRouter key via os.environ/OPENROUTER_API_KEY, injected by
# orclive at launch from the per-user ~/.config/openrouter/key.
#
# Routing: /model local -> H200 ({local_model}), /model opus -> OpenRouter.

model_list:
  # ── Local H200 model ────────────────────────────────────────────────────────
  - model_name: local
    litellm_params:
      model: anthropic/{local_model}
      api_base: {local_url}
      api_key: os.environ/AMBIX_LOCAL_KEY
    model_info:
      description: "{local_model} on 8×H200 (vLLM)"

  # ── OpenRouter (paid; per-user key) ─────────────────────────────────────────
  - model_name: opus
    litellm_params:
      model: anthropic/claude-opus-4.8
      api_base: https://openrouter.ai/api
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      description: "claude-opus-4.8 via OpenRouter"

litellm_settings:
  drop_params: true

general_settings:
  # No master key — bound to 127.0.0.1 on a per-user port by orclive.
  disable_spend_logs: true
"""
