"""Generator for the ``orclive`` LiteLLM routing config.

``orclive`` runs a per-user LiteLLM proxy that lets one Claude Code session
route different tiers to different backends: the bulk tiers (sonnet, haiku) to
the **local** H200 model, and the heavy opus tier to **OpenRouter**. The proxy
needs a YAML config; this module generates it from :class:`SiteConfig` — the
same source-of-truth pattern as ``clive`` — so the local endpoint and served
model never drift, and the file is synced repo → ``/work`` on ``--deploy``.

The config is **secret-free**: the OpenRouter key is referenced as
``os.environ/OPENROUTER_API_KEY`` and supplied by ``orclive`` at proxy launch
from the per-user ``~/.config/openrouter/key``. Edit routing by editing this
generator (the YAML below) and re-deploying — do not hand-edit the ``/work``
copy.

Claude Code requests tier model names ``ambix-{{sonnet,haiku,opus}}`` (set by
``orclive`` via ``ANTHROPIC_DEFAULT_*_MODEL``); LiteLLM maps each to its backend.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from imas_ambix.agent.profile import SiteConfig


def generate_litellm_config(site: SiteConfig, local_model: str) -> str:
    """Render the orclive LiteLLM routing YAML for *site*.

    Parameters
    ----------
    site:
        Cluster config — supplies the local endpoint URL.
    local_model:
        ``served_name`` of the local model (the sonnet/haiku backend).
    """
    local_url = site.default_url
    return f"""# imas-ambix — orclive LiteLLM routing config.
#
# GENERATED by `imas-ambix agent clive --deploy` from SiteConfig (same pattern
# as clive). Do NOT hand-edit the deployed /work copy — edit the generator
# (imas_ambix/agent/litellm_config.py) and re-deploy, or it will be overwritten.
#
# SECRET-FREE: the OpenRouter key is referenced via os.environ/OPENROUTER_API_KEY
# and injected by orclive at launch from the per-user ~/.config/openrouter/key.
# Nothing here is a secret, so it is safe on group-shared GPFS.
#
# Routing: Claude Code requests model names ambix-sonnet / ambix-haiku /
# ambix-opus (orclive sets these via ANTHROPIC_DEFAULT_*_MODEL). Edit the
# `model:` / `api_base:` below to change which tier goes where.

model_list:
  # ── Bulk tiers → LOCAL H200 model (fast, free, on-cluster) ──────────────────
  - model_name: ambix-sonnet
    litellm_params:
      model: anthropic/{local_model}
      api_base: {local_url}
      api_key: os.environ/AMBIX_LOCAL_KEY

  - model_name: ambix-haiku
    litellm_params:
      model: anthropic/{local_model}
      api_base: {local_url}
      api_key: os.environ/AMBIX_LOCAL_KEY

  # ── Heavy tier → OpenRouter burst (paid; per-user key) ──────────────────────
  - model_name: ambix-opus
    litellm_params:
      model: anthropic/claude-opus-4.8
      api_base: https://openrouter.ai/api
      api_key: os.environ/OPENROUTER_API_KEY

litellm_settings:
  drop_params: true

general_settings:
  # No master key — bound to 127.0.0.1 on a per-user port by orclive.
  disable_spend_logs: true
"""
