"""Generator for the ``clive`` LiteLLM routing config.

``clive`` runs a per-user LiteLLM proxy when an OpenRouter key is present,
routing different model names to different backends:

  local / haiku  →  local H200 model
  sonnet / opus  →  OpenRouter (claude-sonnet-4.6 / claude-opus-4.8)
  gpt-5.5 / glm-5.2  →  OpenRouter

The config is **secret-free**: the OpenRouter key is referenced as
``os.environ/OPENROUTER_API_KEY`` and supplied by ``clive`` at launch from the
per-user ``~/.config/openrouter/key``. Edit routing by editing this generator
(the YAML below) and re-deploying — do not hand-edit the ``/work`` copy.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from imas_ambix.agent.profile import SiteConfig


def generate_litellm_config(site: SiteConfig, local_model: str) -> str:
    """Render the clive LiteLLM routing YAML for *site*.

    Six-entry router mapping Claude Code tier names plus extras to their
    backends.  ``model_info.description`` carries the actual model info.

    Parameters
    ----------
    site:
        Cluster config — supplies the local endpoint URL.
    local_model:
        ``served_name`` of the local model (e.g. ``deepseek-v4-flash``).
    """
    local_url = site.default_url
    return f"""# imas-ambix — clive LiteLLM routing config.
#
# GENERATED by `imas-ambix agent clive --deploy` from SiteConfig. Do NOT
# hand-edit the deployed /work copy — edit the generator
# (imas_ambix/agent/litellm_config.py) and re-deploy.
#
# SECRET-FREE: OpenRouter key via os.environ/OPENROUTER_API_KEY, injected by
# clive at launch from the per-user ~/.config/openrouter/key.
#
# Model tiers: Default (local), Sonnet (OR), Opus (OR), Haiku (local).
# Extra OR models: gpt-5.5, glm-5.2 (use --model <name>).

model_list:
  # ── Local H200 model (also serves the haiku tier) ─────────────────────────
  - model_name: local
    litellm_params:
      model: anthropic/{local_model}
      api_base: {local_url}
      api_key: os.environ/AMBIX_LOCAL_KEY
    model_info:
      description: "{local_model} on 8×H200 (vLLM)"

  - model_name: haiku
    litellm_params:
      model: anthropic/{local_model}
      api_base: {local_url}
      api_key: os.environ/AMBIX_LOCAL_KEY
    model_info:
      description: "{local_model} (haiku tier → local)"

  # ── OpenRouter tiers (paid; per-user key) ─────────────────────────────────
  - model_name: sonnet
    litellm_params:
      model: anthropic/claude-sonnet-4.6
      api_base: https://openrouter.ai/api
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      description: "claude-sonnet-4.6 via OpenRouter"

  - model_name: opus
    litellm_params:
      model: anthropic/claude-opus-4.8
      api_base: https://openrouter.ai/api
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      description: "claude-opus-4.8 via OpenRouter"

  # ── Extra OR models (use --model <name>) ──────────────────────────────────
  - model_name: gpt-5.5
    litellm_params:
      model: openai/gpt-5.5
      api_base: https://openrouter.ai/api
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      description: "GPT-5.5 via OpenRouter"

  - model_name: glm-5.2
    litellm_params:
      model: z-ai/glm-5.2
      api_base: https://openrouter.ai/api
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      description: "GLM-5.2 via OpenRouter"

litellm_settings:
  drop_params: true

general_settings:
  # No master key — bound to 127.0.0.1 on a per-user port by clive.
  disable_spend_logs: true
"""
