# ruff: noqa: E501 — embeds shell/systemd templates; line length is governed by
# the generated artifacts, not Python style.
"""Generator for the per-user ``imas-ambix-llm`` systemd unit + env helper.

clive's OpenRouter routing needs a LiteLLM proxy, and starting it per-invocation
costs 10-20 s (the litellm import). Instead we run it as a **per-user**
``systemd --user`` service that stays alive across clive runs: clive does an
idempotent ``systemctl --user start imas-ambix-llm`` (instant when already up)
and connects to the fixed proxy port.

Per-user, NOT shared: the service runs as the invoking user with *their own*
OpenRouter key, bound to ``127.0.0.1`` only (never a public/shared endpoint, so
no shared-key / shared-budget exposure). A user without an OR key never starts
it — clive falls back to the direct local route.

Two artifacts, both generated from :class:`SiteConfig` and installed by
``imas-ambix agent clive --deploy``:

- ``imas-ambix-llm-env.sh`` — a deployed helper that writes a mode-600 env file
  (OR key + local key) into ``$XDG_RUNTIME_DIR``. Keeping this logic in a script
  (not crammed into the unit with line-continuations) avoids systemd quoting
  pitfalls. **Secret-free** — it *reads* the per-user key file at runtime.
- ``imas-ambix-llm.service`` — the systemd --user unit that runs the helper
  (ExecStartPre) then launches litellm bound to 127.0.0.1.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from imas_ambix.agent.profile import SiteConfig

# Fixed loopback port for the per-user proxy. Per-user + 127.0.0.1-bound, so a
# single fixed port is fine (one proxy per user session, not shared).
LITELLM_PORT = 18399


def generate_litellm_env_helper(site: SiteConfig) -> str:
    """Render the ExecStartPre env-file builder script.

    Writes ``$XDG_RUNTIME_DIR/imas-ambix-llm.env`` (mode 600) with the per-user
    OpenRouter key and the shared local key. Secret-free: reads the per-user
    ``~/.config/openrouter/key`` at runtime.
    """
    local_key_file = str(site.api_key_file)
    return f"""#!/usr/bin/env bash
# GENERATED — env-file builder for imas-ambix-llm.service. Edit the generator
# (imas_ambix/agent/litellm_service.py) and re-deploy.
set -euo pipefail
umask 077
_out="${{XDG_RUNTIME_DIR:-/tmp}}/imas-ambix-llm.env"
_or=""
[[ -r "$HOME/.config/openrouter/key" ]] && _or="$(tr -d '[:space:]' < "$HOME/.config/openrouter/key")"
_local="no-auth"
if [[ -r "{local_key_file}" ]]; then
    _k="$(grep -E '^[[:space:]]*AMBIX_AGENT_API_KEY[[:space:]]*=' "{local_key_file}" 2>/dev/null | tail -1 | sed -E 's/[^=]*=//; s/^["'"'"']//; s/["'"'"']$//' || true)"
    [[ -n "$_k" ]] && _local="$_k"
fi
{{
    printf 'OPENROUTER_API_KEY=%s\\n' "$_or"
    printf 'AMBIX_LOCAL_KEY=%s\\n' "$_local"
}} > "$_out"
"""


def generate_litellm_service(site: SiteConfig) -> str:
    """Render the ``imas-ambix-llm.service`` systemd --user unit.

    Calls the deployed env helper (ExecStartPre), then runs litellm bound to
    127.0.0.1:LITELLM_PORT with the deployed routing config.
    """
    cfg = str(site.litellm_config_path)
    helper = str(site.litellm_config_path.with_name("imas-ambix-llm-env.sh"))
    return f"""# imas-ambix per-user LiteLLM proxy for clive OpenRouter routing.
#
# GENERATED by `imas-ambix agent clive --deploy`. Per-user (`systemctl --user`),
# bound to 127.0.0.1 only — NOT a shared/public service. Uses the invoking
# user's own ~/.config/openrouter/key. Secret-free: the key is loaded into the
# unit's env at start by the env-helper script, never written into this file.

[Unit]
Description=imas-ambix LiteLLM proxy (clive OpenRouter routing, per-user)
After=network.target

[Service]
Type=simple
# Build the per-user env file (OR key + local key) → $XDG_RUNTIME_DIR, then run.
# EnvironmentFile is '-' (optional): ExecStartPre creates it, so it does not yet
# exist when systemd validates the unit at load — a non-optional ref would fail
# with Result=resources.
ExecStartPre=/bin/bash {helper}
EnvironmentFile=-%t/imas-ambix-llm.env
ExecStart=%h/.local/bin/litellm --config {cfg} --host 127.0.0.1 --port {LITELLM_PORT}
ExecStopPost=/bin/rm -f %t/imas-ambix-llm.env
Restart=on-failure
RestartSec=5
TimeoutStartSec=120

[Install]
WantedBy=default.target
"""
