# ruff: noqa: E501 — the module is mostly an embedded bash template; line length
# is governed by the generated shell script, not Python style.
"""Generator for the ``orclive`` launcher — two-model routing via LiteLLM.

``orclive`` runs a per-user LiteLLM proxy with just two routes:
``local`` (the H200 model) and ``opus`` (OpenRouter). Set your
session model with ``/model local`` or ``/model opus`` to switch.
(For local-only, use ``clive``; for all-OpenRouter, use ``orclaude``.)

SECURITY — safe on group-shared GPFS: the script holds NO secret. The OpenRouter
key is read at runtime from the per-user ``~/.config/openrouter/key`` (same file
``orclaude`` uses) and exported only into the LiteLLM subprocess. Routing lives
entirely in the deployed ``litellm_config.yaml`` (also secret-free) — edit
routing there, not here.

Generated from :class:`SiteConfig` like ``clive``; synced repo → ``/work`` via
``imas-ambix agent clive --deploy``.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from imas_ambix.agent.profile import SiteConfig


def generate_orclive_script(site: SiteConfig, default_model: str) -> str:
    """Render the ``orclive`` advisor launcher for *site*.

    Parameters
    ----------
    site:
        Cluster config — supplies the local endpoint, key file, and the
        deployed LiteLLM config path.
    default_model:
        ``served_name`` of the local model (unused at runtime — the live model
        is auto-detected — but kept for parity / messaging).
    """
    local_url = site.default_url
    local_key_file = str(site.api_key_file)
    litellm_cfg = str(site.litellm_config_path)
    return f'''#!/usr/bin/env bash
# orclive — two-model router: /model local (H200), /model opus (OpenRouter).
#
# GENERATED by `imas-ambix agent clive --deploy`. Do NOT edit in place — edit
# the generator (imas_ambix/agent/orclive.py) and re-deploy.
#
# SECURITY: holds NO secret. The OpenRouter key is read at runtime from the
# per-user $ORCLIVE_OR_KEY_FILE (default ~/.config/openrouter/key) and exported
# only into the LiteLLM subprocess. Routing lives in the LiteLLM config
# ({litellm_cfg}) — edit routing there.
#
# Sibling launchers:  clive = local-only (everyone) · orclaude = all-OpenRouter.

set -euo pipefail

LITELLM_CONFIG="${{ORCLIVE_LITELLM_CONFIG:-{litellm_cfg}}}"
ORCLIVE_OR_KEY_FILE="${{ORCLIVE_OR_KEY_FILE:-$HOME/.config/openrouter/key}}"
ORCLIVE_LOCAL_URL="${{AMBIX_AGENT_URL:-{local_url}}}"
ORCLIVE_LOCAL_KEY_FILE="${{AMBIX_AGENT_KEY_FILE:-{local_key_file}}}"

usage() {{
    cat >&2 <<'USAGE'
orclive — two-model router for Claude Code: /model local (H200),
/model opus (OpenRouter). Routing is in the LiteLLM config.

  orclive [-h|--help] [agent-args...]

Local-only?  use `clive`.   All-OpenRouter?  use `orclaude`.
Edit routing: the deployed litellm_config.yaml (generated — edit the repo
generator imas_ambix/agent/litellm_config.py and re-deploy).
OpenRouter key (per-user, mode 600): ~/.config/openrouter/key
USAGE
}}

case "${{1:-}}" in -h|--help) usage; exit 0 ;; esac

command -v claude  >/dev/null 2>&1 || {{ echo "orclive: 'claude' not on PATH — install Claude Code." >&2; exit 127; }}
command -v litellm >/dev/null 2>&1 || {{ echo "orclive: 'litellm' not on PATH (pip/uv install litellm) — needed for routing." >&2; exit 127; }}
[[ -r "$LITELLM_CONFIG" ]] || {{ echo "orclive: routing config not found: $LITELLM_CONFIG (run: imas-ambix agent clive --deploy)" >&2; exit 1; }}

# ── Per-user OpenRouter key (never shared) → exported into the proxy only ────
if [[ -n "${{OPENROUTER_API_KEY:-}}" ]]; then
    export OPENROUTER_API_KEY
elif [[ -r "$ORCLIVE_OR_KEY_FILE" ]]; then
    export OPENROUTER_API_KEY="$(tr -d '[:space:]' < "$ORCLIVE_OR_KEY_FILE")"
else
    echo "orclive: no OpenRouter key at $ORCLIVE_OR_KEY_FILE (and \\$OPENROUTER_API_KEY unset)." >&2
    echo "         Create it (mode 600), or use clive for local-only." >&2
    exit 1
fi

# ── Local server key (keyless server → dummy) → exported for the local route ─
AMBIX_LOCAL_KEY="no-auth"
if [[ -r "$ORCLIVE_LOCAL_KEY_FILE" ]]; then
    _k="$(grep -E '^[[:space:]]*AMBIX_AGENT_API_KEY[[:space:]]*=' "$ORCLIVE_LOCAL_KEY_FILE" 2>/dev/null | tail -1 | sed -E 's/[^=]*=//; s/^["'"'"']//; s/["'"'"']$//' || true)"
    [[ -n "$_k" ]] && AMBIX_LOCAL_KEY="$_k"
fi
export AMBIX_LOCAL_KEY

# ── Start the per-user LiteLLM proxy on a free port; tear down on exit ────────
PORT="$(python3 -c 'import socket;s=socket.socket();s.bind(("127.0.0.1",0));print(s.getsockname()[1]);s.close()')"
_log="$(mktemp -t orclive-litellm.XXXXXX.log)"
litellm --config "$LITELLM_CONFIG" --host 127.0.0.1 --port "$PORT" > "$_log" 2>&1 &
_lpid=$!
cleanup() {{ kill "$_lpid" 2>/dev/null || true; rm -f "$_log"; }}
trap cleanup EXIT INT TERM

for _i in $(seq 1 40); do
    (exec 3<>"/dev/tcp/127.0.0.1/$PORT") 2>/dev/null && {{ exec 3>&- 3<&-; break; }}
    kill -0 "$_lpid" 2>/dev/null || {{ echo "orclive: LiteLLM failed to start:" >&2; tail -8 "$_log" >&2; exit 1; }}
    sleep 0.5
done

echo "orclive: router up -- /model local (H200), /model opus -> OpenRouter." >&2

# Point Claude Code at the proxy; use /model to switch routes
ANTHROPIC_BASE_URL="http://127.0.0.1:$PORT" \\
ANTHROPIC_AUTH_TOKEN="orclive" \\
ANTHROPIC_API_KEY="" \\
CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1 \\
claude "$@"
'''
