# ruff: noqa: E501 — the module is mostly an embedded bash template; line length
# is governed by the generated shell script, not Python style.
"""Generator for the ``orclive`` launcher — hybrid local + OpenRouter routing.

``orclive`` ("OpenRouter + clive") is the *key-holder* counterpart to ``clive``:
it routes some Claude Code tiers to the **local** H200 model and bursts others
(typically opus) to **OpenRouter**. Claude Code has a single ``ANTHROPIC_BASE_URL``,
so per-tier routing requires a tiny **per-user LiteLLM proxy** that orclive
starts on the fly, routes by model name, and tears down on exit.

SECURITY — why this is safe to ship on shared GPFS alongside ``clive``:
the generated script carries **NO secret**. The OpenRouter key is read at
runtime from the **per-user** ``~/.config/openrouter/key`` (the same file
``orclaude`` uses) — never from any group-readable ``/work`` file. A user
without that key gets a clear setup message and orclive refuses to start the
OR route. Each user runs their own ephemeral proxy with their own key.

Like ``clive``, this is generated from :class:`SiteConfig` so the local
endpoint never drifts, and synced repo → ``/work`` via ``orclive --deploy``.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from imas_ambix.agent.profile import SiteConfig


def generate_orclive_script(site: SiteConfig, default_model: str) -> str:
    """Render the ``orclive`` hybrid launcher for *site*.

    Parameters
    ----------
    site:
        Cluster config supplying the local endpoint URL and key-file path.
    default_model:
        ``served_name`` fallback for the local model if ``/v1/models`` query
        fails.
    """
    url = site.default_url
    key_file = str(site.api_key_file)
    return f'''#!/usr/bin/env bash
# orclive — hybrid launcher: local H200 model for sonnet/haiku, OpenRouter for opus.
#
# GENERATED by `imas-ambix agent orclive --deploy`. Do NOT edit in place — edit
# the generator (imas_ambix/agent/orclive.py) and re-deploy.
#
# SECURITY: this script holds NO secret. The OpenRouter key is read at runtime
# from the per-user $ORCLIVE_OR_KEY_FILE (default ~/.config/openrouter/key).
# Nothing here is shared; each user supplies their own key from their own home.
#
# HOW IT WORKS: Claude Code uses ONE base URL for all tiers, so per-tier routing
# needs a router. orclive starts a tiny per-user LiteLLM proxy (on a per-user
# port), routes model-name → backend (local vs OpenRouter), points Claude Code
# at it, and tears it down on exit.
#
# Usage:
#   orclive [--hybrid|--local-only|--or-only] [agent-args...]
#   orclive "refactor this"                 # hybrid (default): sonnet/haiku→local, opus→OR
#   orclive --local-only "quick edit"       # all tiers → local H200 (no OR; same as clive)
#   orclive --or-only "hard problem"        # all tiers → OpenRouter
#
# Per-user config (optional) at $ORCLIVE_CONFIG (default ~/.config/orclive/config):
#   a dotenv-style file overriding any of:
#     ORCLIVE_LOCAL_TIERS="sonnet haiku"        # which tiers route local
#     ORCLIVE_OR_TIERS="opus"                   # which tiers route to OpenRouter
#     ORCLIVE_OR_MODEL="anthropic/claude-opus-4.8"   # OR model for OR tiers
#     ORCLIVE_OR_BASE="https://openrouter.ai/api"    # OR Anthropic endpoint
#     ORCLIVE_LOCAL_URL="{url}"                  # local H200 endpoint
#     ORCLIVE_OR_KEY_FILE="$HOME/.config/openrouter/key"

set -euo pipefail

# ── Defaults (overridable via per-user config / env / flags) ─────────────────
ORCLIVE_LOCAL_URL="${{ORCLIVE_LOCAL_URL:-${{AMBIX_AGENT_URL:-{url}}}}}"
ORCLIVE_LOCAL_KEY_FILE="${{ORCLIVE_LOCAL_KEY_FILE:-{key_file}}}"
ORCLIVE_LOCAL_MODEL_FALLBACK="{default_model}"
ORCLIVE_OR_KEY_FILE="${{ORCLIVE_OR_KEY_FILE:-$HOME/.config/openrouter/key}}"
ORCLIVE_OR_BASE="${{ORCLIVE_OR_BASE:-https://openrouter.ai/api}}"
ORCLIVE_OR_MODEL="${{ORCLIVE_OR_MODEL:-anthropic/claude-opus-4.8}}"
ORCLIVE_LOCAL_TIERS="${{ORCLIVE_LOCAL_TIERS:-sonnet haiku}}"
ORCLIVE_OR_TIERS="${{ORCLIVE_OR_TIERS:-opus}}"
ORCLIVE_PORT="${{ORCLIVE_PORT:-0}}"   # 0 → pick a free per-user port
MODE="hybrid"

# Load optional per-user config (dotenv-style; never group-shared).
_cfg="${{ORCLIVE_CONFIG:-$HOME/.config/orclive/config}}"
if [[ -r "$_cfg" ]]; then
    # shellcheck disable=SC1090
    set -a; source "$_cfg"; set +a
fi

usage() {{
    cat >&2 <<'USAGE'
orclive — hybrid local + OpenRouter launcher for Claude Code (key-holders).

  orclive [--hybrid|--local-only|--or-only] [-h|--help] [agent-args...]

  --hybrid       (default) sonnet/haiku → local H200, opus → OpenRouter.
  --local-only   all tiers → local H200 (identical to `clive`; no OR key needed).
  --or-only      all tiers → OpenRouter.

Config (per-user, optional): ~/.config/orclive/config — see header for keys.
OpenRouter key (per-user): ~/.config/openrouter/key (mode 600).
USAGE
}}

ARGS=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --hybrid)     MODE="hybrid"; shift ;;
        --local-only) MODE="local";  shift ;;
        --or-only)    MODE="or";     shift ;;
        -h|--help)    usage; exit 0 ;;
        --) shift; ARGS+=("$@"); break ;;
        *)  ARGS+=("$1"); shift ;;
    esac
done

# ── Read the per-user OpenRouter key (only when an OR route is needed) ────────
OR_KEY=""
read_or_key() {{
    if [[ -n "${{OPENROUTER_API_KEY:-}}" ]]; then printf '%s' "$OPENROUTER_API_KEY"; return 0; fi
    [[ -r "$ORCLIVE_OR_KEY_FILE" ]] || return 1
    tr -d '[:space:]' < "$ORCLIVE_OR_KEY_FILE"
}}
if [[ "$MODE" != "local" ]]; then
    OR_KEY="$(read_or_key || true)"
    if [[ -z "$OR_KEY" ]]; then
        echo "orclive: no OpenRouter key at $ORCLIVE_OR_KEY_FILE (and \\$OPENROUTER_API_KEY unset)." >&2
        echo "         Create it (mode 600) or run with --local-only to skip OpenRouter." >&2
        exit 1
    fi
fi

# ── Read the local server key (keyless server → dummy) ───────────────────────
LOCAL_KEY=""
if [[ -r "$ORCLIVE_LOCAL_KEY_FILE" ]]; then
    LOCAL_KEY="$(grep -E '^[[:space:]]*AMBIX_AGENT_API_KEY[[:space:]]*=' "$ORCLIVE_LOCAL_KEY_FILE" 2>/dev/null | tail -1 | sed -E 's/[^=]*=//; s/^["'"'"']//; s/["'"'"']$//' || true)"
fi
[[ -n "$LOCAL_KEY" ]] || LOCAL_KEY="no-auth"

# ── Resolve the local served model from /v1/models ───────────────────────────
LOCAL_MODEL="$(curl -s --max-time 5 -H "Authorization: Bearer $LOCAL_KEY" "$ORCLIVE_LOCAL_URL/v1/models" 2>/dev/null \\
    | grep -oE '"id"[[:space:]]*:[[:space:]]*"[^"]+"' | head -1 | sed -E 's/.*"id"[[:space:]]*:[[:space:]]*"([^"]+)".*/\\1/')"
if [[ -z "$LOCAL_MODEL" ]]; then
    LOCAL_MODEL="$ORCLIVE_LOCAL_MODEL_FALLBACK"
    echo "orclive: local server not reachable / no model; using fallback '$LOCAL_MODEL'." >&2
fi

# ── --or-only and --local-only need no router: point Claude Code straight there
launch_claude() {{ # $1 base_url  $2 auth_token  $3 model-for-all-tiers
    ANTHROPIC_BASE_URL="$1" \\
    ANTHROPIC_AUTH_TOKEN="$2" \\
    ANTHROPIC_API_KEY="" \\
    ANTHROPIC_DEFAULT_OPUS_MODEL="$3" \\
    ANTHROPIC_DEFAULT_SONNET_MODEL="$3" \\
    ANTHROPIC_DEFAULT_HAIKU_MODEL="$3" \\
    ANTHROPIC_MODEL="$3" \\
    CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1 \\
    exec claude "${{ARGS[@]}}"
}}

command -v claude >/dev/null 2>&1 || {{ echo "orclive: 'claude' not on PATH — install Claude Code." >&2; exit 127; }}

if [[ "$MODE" == "local" ]]; then
    launch_claude "$ORCLIVE_LOCAL_URL" "$LOCAL_KEY" "$LOCAL_MODEL"
fi
if [[ "$MODE" == "or" ]]; then
    launch_claude "$ORCLIVE_OR_BASE" "$OR_KEY" "$ORCLIVE_OR_MODEL"
fi

# ── --hybrid: start a per-user LiteLLM router that splits tiers by model name ─
command -v litellm >/dev/null 2>&1 || {{ echo "orclive: 'litellm' not on PATH — needed for --hybrid (pip/uv install litellm), or use --local-only / --or-only." >&2; exit 127; }}

# Per-user scratch for the ephemeral config + key (mode 700).
_run="${{XDG_RUNTIME_DIR:-/tmp}}/orclive.$$"
mkdir -p "$_run"; chmod 700 "$_run"
cleanup() {{ [[ -n "${{_lpid:-}}" ]] && kill "$_lpid" 2>/dev/null || true; rm -rf "$_run"; }}
trap cleanup EXIT INT TERM

# Pick a free port if not pinned.
if [[ "$ORCLIVE_PORT" == "0" ]]; then
    ORCLIVE_PORT="$(python3 -c 'import socket;s=socket.socket();s.bind(("127.0.0.1",0));print(s.getsockname()[1]);s.close()')"
fi

# Build the LiteLLM model_list: one model_name per Claude Code tier model,
# routed to local or OpenRouter. The keys go via env (not written to disk).
export _ORCLIVE_OR_KEY="$OR_KEY" _ORCLIVE_LOCAL_KEY="$LOCAL_KEY"
{{
    echo "model_list:"
    for t in $ORCLIVE_LOCAL_TIERS; do
        echo "  - model_name: orclive-$t"
        echo "    litellm_params:"
        echo "      model: anthropic/$LOCAL_MODEL"
        echo "      api_base: $ORCLIVE_LOCAL_URL"
        echo "      api_key: os.environ/_ORCLIVE_LOCAL_KEY"
    done
    for t in $ORCLIVE_OR_TIERS; do
        echo "  - model_name: orclive-$t"
        echo "    litellm_params:"
        echo "      model: $ORCLIVE_OR_MODEL"
        echo "      api_base: $ORCLIVE_OR_BASE"
        echo "      api_key: os.environ/_ORCLIVE_OR_KEY"
    done
}} > "$_run/config.yaml"
chmod 600 "$_run/config.yaml"

litellm --config "$_run/config.yaml" --host 127.0.0.1 --port "$ORCLIVE_PORT" > "$_run/litellm.log" 2>&1 &
_lpid=$!

# Wait for the proxy to come up.
for _i in $(seq 1 30); do
    (exec 3<>"/dev/tcp/127.0.0.1/$ORCLIVE_PORT") 2>/dev/null && {{ exec 3>&- 3<&-; break; }}
    kill -0 "$_lpid" 2>/dev/null || {{ echo "orclive: LiteLLM failed to start — see $_run/litellm.log" >&2; tail -5 "$_run/litellm.log" >&2; exit 1; }}
    sleep 0.5
done

echo "orclive: hybrid router up on 127.0.0.1:$ORCLIVE_PORT — local[$ORCLIVE_LOCAL_TIERS]=$LOCAL_MODEL  OR[$ORCLIVE_OR_TIERS]=$ORCLIVE_OR_MODEL" >&2

# Point Claude Code at the router; each tier requests orclive-<tier>, which
# LiteLLM maps to local or OpenRouter.
ANTHROPIC_BASE_URL="http://127.0.0.1:$ORCLIVE_PORT" \\
ANTHROPIC_AUTH_TOKEN="orclive" \\
ANTHROPIC_API_KEY="" \\
ANTHROPIC_DEFAULT_OPUS_MODEL="orclive-opus" \\
ANTHROPIC_DEFAULT_SONNET_MODEL="orclive-sonnet" \\
ANTHROPIC_DEFAULT_HAIKU_MODEL="orclive-haiku" \\
CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1 \\
claude "${{ARGS[@]}}"
'''
